spring:
    profiles:
        active:
        - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: mavenspringcloud-config-bigjava-dev
---
spring:
  profiles: test   #测试环境
  application: 
    name: mavenspringcloud-config-bigjava-test
#  请保存为UTF-8格式        