spring:
    profiles:
        active:
        - dev
---
server:
    port: 8001
spring:
    profiles: dev  
    application:
        name: mavenspringcloud-config-user-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/exam_8001
        username: root
        password: root
        dbcp2:
            min-idle: 5
            initial-size: 5
            max-total: 5
            max-wait-millis: 200
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: org.bigjava.entity # 所有entity别名类所在包
    mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                   # mapper映射文件
    
eureka: 
    client: #客户端注册进eureka服务列表内
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka
    instance:
        instance-id: mavenSpringCloud-8001 #自定义服务名称信息
        prefer-ip-address: true     #访问路径可以显示IP地址
            
info:
  app.name: bigjava
  company.name: www.bigjava.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$     

---
server:
    port: 8001
spring:
    profiles: test  
    application:
        name: mavenspringcloud-config-user-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/exam_8002
        username: root
        password: root
        dbcp2:
            min-idle: 5
            initial-size: 5
            max-total: 5
            max-wait-millis: 200
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: org.bigjava.entity # 所有entity别名类所在包
    mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                   # mapper映射文件
    
eureka: 
    client: #客户端注册进eureka服务列表内
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka
    instance:
        instance-id: mavenSpringCloud-8002 #自定义服务名称信息
        prefer-ip-address: true     #访问路径可以显示IP地址
            
info:
  app.name: bigjava
  company.name: www.bigjava.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$              
